apps:
  # ---------- TEST ENVS ----------
  - name: admin
    env: test
    domain: admin.test.simpliiexchange.com
    port: 3101

  # ---------- PROD ENVS----------
  - name: admin
    env: prod
    domain: admin.simpliiexchange.com
    port: 3201
  - name: landing
    env: prod
    domain: simpliiexchange.com
    port: 3200
